Repository DCNsProjects/WantIt, pull requests merged in 2024-04, with the labels that each got.

#1 Feat/auction item
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/AuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/AuctionItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/AuctionItemService.java
  src/main/java/io/dcns/wantitauction/global/dto/ExceptionDto.java
Labels: enhancement

#2 Feat/user
  src/main/java/io/dcns/wantitauction/domain/user/controller/UserController.java
  src/main/java/io/dcns/wantitauction/domain/user/dto/LoginRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/user/dto/SignupRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/user/entity/User.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserJpaRepository.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserRepository.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserRepositoryImpl.java
  src/main/java/io/dcns/wantitauction/domain/user/service/UserService.java
  src/main/java/io/dcns/wantitauction/global/config/JpaConfig.java
  src/main/java/io/dcns/wantitauction/global/config/PasswordConfig.java
  src/main/java/io/dcns/wantitauction/global/config/WebSecurityConfig.java
  src/main/java/io/dcns/wantitauction/global/exception/NotMatchException.java
  src/main/java/io/dcns/wantitauction/global/filter/AuthenticationFilter.java
  src/main/java/io/dcns/wantitauction/global/filter/AuthorizationFilter.java
  src/main/java/io/dcns/wantitauction/global/impl/UserDetailsImpl.java
  src/main/java/io/dcns/wantitauction/global/impl/UserDetailsServiceImpl.java
  src/main/java/io/dcns/wantitauction/global/jwt/JwtUtil.java
  src/main/java/io/dcns/wantitauction/global/jwt/TokenState.java
  src/main/java/io/dcns/wantitauction/global/jwt/entity/RefreshTokenEntity.java
  src/main/java/io/dcns/wantitauction/global/jwt/repository/RefreshTokenJpaRepository.java
  src/main/java/io/dcns/wantitauction/global/jwt/repository/TokenRepository.java
  src/main/java/io/dcns/wantitauction/global/jwt/repository/TokenRepositoryImpl.java
  src/main/java/io/dcns/wantitauction/global/timestamp/Timestamped.java
Labels: enhancement

#3 Feat/my auction item
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/MyAuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/CreateProductRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/MyAuctionItemsResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemRepository.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/MyAuctionItemService.java
Labels: enhancement

#4 Feat/point
  src/main/java/io/dcns/wantitauction/domain/point/controller/PointController.java
  src/main/java/io/dcns/wantitauction/domain/point/dto/PointChangedResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/point/dto/PointRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/point/dto/PointResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/point/entity/Point.java
  src/main/java/io/dcns/wantitauction/domain/point/repository/PointRepository.java
  src/main/java/io/dcns/wantitauction/domain/point/service/PointService.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/controller/PointLogController.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/dto/PointLogResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/entity/PointLog.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/repository/PointLogQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/service/PointLogService.java
Labels: enhancement

#5 Feat/my auction item
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/MyAuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/UpdateMyItemRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemRepository.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/MyAuctionItemService.java
  src/main/java/io/dcns/wantitauction/global/exception/ExceptionController.java
Labels: enhancement

#8 Feat/my auction item
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/MyAuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/CreateProductRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/UpdateMyItemRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/MyAuctionItemService.java
Labels: bug, enhancement

#7 ♻️ refactor : NumberUtils.toLong 사용하여 예외처리
  build.gradle
  src/main/java/io/dcns/wantitauction/global/filter/AuthorizationFilter.java
Labels: enhancement

#9 ✨ feat : 낙찰 상품 목록/단건 조회 API 구현
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/AuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/FinishedItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/AuctionItemService.java
Labels: enhancement

#11 🔧 chore : AuctionItem에 낙찰자 ID(winnerId) 추가
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/FinishedItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
Labels: enhancement

#12 ✨ feat : 좋아요(찜하기) 기능 등록 및 취소, 좋아요 조회 기능 구현
  src/main/java/io/dcns/wantitauction/domain/like/controller/LikeController.java
  src/main/java/io/dcns/wantitauction/domain/like/dto/LikeResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/like/entity/Like.java
  src/main/java/io/dcns/wantitauction/domain/like/repository/LikeRepository.java
  src/main/java/io/dcns/wantitauction/domain/like/service/LikeService.java
Labels: enhancement

#13 Feat/my auction item
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/MyAuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemRepository.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/MyAuctionItemService.java
Labels: bug, enhancement

#14 🔧 chore : 반환 타입 변경
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/MyAuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/MyAuctionItemService.java
Labels: bug

#15 ♻️ recycle : 좋아요(찜하기) 등록 및 취소, 조회 부분 리팩토링 (query DSL로 수정 포함)
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemRepository.java
  src/main/java/io/dcns/wantitauction/domain/like/dto/LikeRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/like/entity/Like.java
  src/main/java/io/dcns/wantitauction/domain/like/repository/LikeQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/like/repository/LikeRepository.java
  src/main/java/io/dcns/wantitauction/domain/like/service/LikeService.java
Labels: documentation

#16 feat / point
  src/main/java/io/dcns/wantitauction/domain/point/dto/PointChangedResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/point/service/PointService.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/dto/PointLogResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/entity/PointLog.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/entity/PointLogStatus.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/repository/PointLogQueryRepository.java
Labels: enhancement

#17 User
  build.gradle
  src/main/java/io/dcns/wantitauction/domain/user/controller/KaKaoController.java
  src/main/java/io/dcns/wantitauction/domain/user/dto/KakaoUserInfoDto.java
  src/main/java/io/dcns/wantitauction/domain/user/entity/User.java
  src/main/java/io/dcns/wantitauction/domain/user/entity/UserMapper.java
  src/main/java/io/dcns/wantitauction/domain/user/service/KakaoService.java
  src/main/java/io/dcns/wantitauction/domain/user/service/UserService.java
  src/main/java/io/dcns/wantitauction/global/config/RestTemplateConfig.java
  src/main/java/io/dcns/wantitauction/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/css/style.css
  src/main/resources/static/js/basic.js
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: enhancement

#20 ♻️ refactor : DTO 필드 변경
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/CreateProductRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
Labels: bug

#21 :sparkles: feat : 입찰 등록 기능 추가
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/AuctionItemService.java
  src/main/java/io/dcns/wantitauction/domain/bid/controller/BidController.java
  src/main/java/io/dcns/wantitauction/domain/bid/dto/BidRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/bid/dto/BidResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/bid/entity/Bid.java
  src/main/java/io/dcns/wantitauction/domain/bid/repository/BidRepository.java
  src/main/java/io/dcns/wantitauction/domain/bid/service/BidService.java
  src/main/java/io/dcns/wantitauction/domain/point/entity/Point.java
  src/main/java/io/dcns/wantitauction/domain/point/service/PointService.java
Labels: enhancement

#22 User
  src/main/java/io/dcns/wantitauction/domain/user/entity/User.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserJpaRepository.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserRepository.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserRepositoryImpl.java
  src/main/java/io/dcns/wantitauction/domain/user/service/KakaoService.java
  src/main/java/io/dcns/wantitauction/domain/user/viewController/KaKaoViewController.java
  src/main/java/io/dcns/wantitauction/global/config/WebSecurityConfig.java
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: bug, enhancement

#23 Feat/scheduler
  build.gradle
  src/main/java/io/dcns/wantitauction/WantItAuctionApplication.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/event/WinningBidEvent.java
  src/main/java/io/dcns/wantitauction/domain/point/entity/Point.java
  src/main/java/io/dcns/wantitauction/domain/point/service/PointService.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/entity/PointLog.java
  src/main/java/io/dcns/wantitauction/domain/scheduler/Scheduler.java
  src/main/java/io/dcns/wantitauction/global/exception/ExceptionController.java
Labels: enhancement

#24 🔧 chore : 변수명 정리
  Readme.md
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/AuctionItemRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/AuctionItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/FinishedItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/MyAuctionItemsResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/UpdateMyItemRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/bid/dto/BidResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/event/WinningBidEvent.java
  src/main/java/io/dcns/wantitauction/domain/like/entity/Like.java
  src/main/java/io/dcns/wantitauction/domain/point/entity/Point.java
  src/main/java/io/dcns/wantitauction/domain/point/service/PointService.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/dto/PointLogRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/user/dto/KakaoUserInfoDto.java
  src/main/java/io/dcns/wantitauction/domain/user/dto/LoginRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/user/dto/SignupRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/user/service/KakaoService.java
Labels: enhancement

#25 Chore
  Readme.md
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/AuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/MyAuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/AuctionItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/CreateProductRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/FinishedItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/MyAuctionItemsResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/UpdateMyItemRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/AuctionItemService.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/MyAuctionItemService.java
Labels: enhancement

#26 :sparkles: feat : 입찰 조회 기능 추가
  src/main/java/io/dcns/wantitauction/domain/bid/controller/BidController.java
  src/main/java/io/dcns/wantitauction/domain/bid/dto/BidResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/bid/repository/BidQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/bid/service/BidService.java
Labels: enhancement

#27 ✨ feat : 이메일 인증 기능 구현
  build.gradle
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailController.java
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailService.java
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailSignupRequestDto.java
  src/main/java/io/dcns/wantitauction/global/config/RedisConfig.java
  src/main/java/io/dcns/wantitauction/global/config/WebSecurityConfig.java
  src/main/java/io/dcns/wantitauction/global/util/RedisUtil.java
  src/main/resources/application.yml
  src/main/resources/templates/mail.html
Labels: enhancement

#29 Feat/user
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailController.java
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailService.java
Labels: documentation

#28 Feat/point
  src/main/java/io/dcns/wantitauction/domain/point/service/PointService.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/controller/PointLogController.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/dto/PointLogPageableResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/entity/PointLog.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/repository/PointLogQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/pointLog/service/PointLogService.java
Labels: enhancement

#30 Feat/aop
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/MyAuctionItemService.java
  src/main/java/io/dcns/wantitauction/domain/point/service/PointService.java
  src/main/java/io/dcns/wantitauction/global/aop/ForbiddenKeyword.java
  src/main/java/io/dcns/wantitauction/global/aop/ForbiddenKeywordAOP.java
  src/main/java/io/dcns/wantitauction/global/aop/ForbiddenKeywords.java
  src/main/java/io/dcns/wantitauction/global/event/WinningBidEvent.java
  src/main/java/io/dcns/wantitauction/global/scheduler/Scheduler.java
Labels: enhancement

#31 🩹 fix : 카카오 로그인 기능 과 이메일 인증기능이 build.gradle에서 충돌이 나서, 이를 해결함.
  build.gradle
  src/main/java/io/dcns/wantitauction/domain/user/controller/UserController.java
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailService.java
Labels: bug

#32 User
  src/main/java/io/dcns/wantitauction/domain/user/controller/UserController.java
  src/main/java/io/dcns/wantitauction/domain/user/dto/SignupRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/user/entity/User.java
  src/main/java/io/dcns/wantitauction/domain/user/entity/UserMapper.java
  src/main/java/io/dcns/wantitauction/domain/user/entity/UserRoleEnum.java
  src/main/java/io/dcns/wantitauction/domain/user/service/KakaoService.java
  src/main/java/io/dcns/wantitauction/domain/user/service/UserService.java
  src/main/java/io/dcns/wantitauction/global/config/RedisConfig.java
  src/main/java/io/dcns/wantitauction/global/config/WebSecurityConfig.java
  src/main/java/io/dcns/wantitauction/global/filter/AuthorizationFilter.java
  src/main/java/io/dcns/wantitauction/global/impl/UserDetailsImpl.java
  src/main/java/io/dcns/wantitauction/global/impl/UserDetailsServiceImpl.java
  src/main/java/io/dcns/wantitauction/global/jwt/JwtUtil.java
  src/main/java/io/dcns/wantitauction/global/jwt/RefreshToken.java
  src/main/java/io/dcns/wantitauction/global/jwt/RefreshTokenRepository.java
  src/main/java/io/dcns/wantitauction/global/jwt/entity/RefreshTokenEntity.java
  src/main/java/io/dcns/wantitauction/global/jwt/repository/RefreshTokenJpaRepository.java
  src/main/java/io/dcns/wantitauction/global/jwt/repository/TokenRepository.java
  src/main/java/io/dcns/wantitauction/global/jwt/repository/TokenRepositoryImpl.java
Labels: enhancement

#33 ✨ feat : 구글이메일로 인증하기 기능 구현(네이버에서 구글이메일로 변경)
  build.gradle
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailService.java
  src/main/resources/application.yml
Labels: enhancement

#35 ✨ feat : 경매 오픈 로직 구현
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
  src/main/java/io/dcns/wantitauction/global/event/StartAuctionEvent.java
  src/main/java/io/dcns/wantitauction/global/scheduler/Scheduler.java
Labels: enhancement

#34 ✨ feat : 실시간 입찰가격 송출 서비스 구현
  src/main/java/io/dcns/wantitauction/domain/bid/service/BidService.java
  src/main/java/io/dcns/wantitauction/global/event/TopBidChangeEvent.java
  src/main/java/io/dcns/wantitauction/global/exception/ExceptionController.java
  src/main/java/io/dcns/wantitauction/global/exception/LiveBidException.java
  src/main/java/io/dcns/wantitauction/global/sse/LiveBidController.java
  src/main/java/io/dcns/wantitauction/global/sse/LiveBidService.java
Labels: enhancement

#37 ✨ feat : 경매 낙찰 메일 발송 구현
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailService.java
  src/main/java/io/dcns/wantitauction/global/event/WinningBidEvent.java
  src/main/java/io/dcns/wantitauction/global/exception/ExceptionController.java
  src/main/java/io/dcns/wantitauction/global/scheduler/Scheduler.java
Labels: enhancement

#39 :adhesive_bandage: fix : uri 수정
  src/main/java/io/dcns/wantitauction/domain/point/controller/PointController.java
Labels: documentation

#42 :bug: acceessToken에서 user정보(userId)를 가지고 오지 못한 문제 해결
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailService.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserJpaRepository.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserRepository.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserRepositoryImpl.java
  src/main/java/io/dcns/wantitauction/domain/user/service/UserService.java
  src/main/java/io/dcns/wantitauction/global/filter/AuthorizationFilter.java
  src/main/java/io/dcns/wantitauction/global/jwt/JwtUtil.java
  src/main/java/io/dcns/wantitauction/global/jwt/RefreshTokenRepository.java
Labels: bug

#43 Admin API 추가
  src/main/java/io/dcns/wantitauction/domain/admin/controller/AdminController.java
  src/main/java/io/dcns/wantitauction/domain/admin/dto/UserPageableResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/admin/dto/UsersResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/admin/service/AdminService.java
  src/main/java/io/dcns/wantitauction/domain/user/dto/SignupRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailService.java
  src/main/java/io/dcns/wantitauction/domain/user/entity/User.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/user/service/UserService.java
  src/main/resources/templates/mail.html
Labels: bug, enhancement

#47 Feat/scheduler
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItemEnum.java
  src/main/java/io/dcns/wantitauction/global/scheduler/Scheduler.java
Labels: bug

#51 ✅ test : AuctionItemService 테스트 코드 추가
  src/test/java/io/dcns/wantitauction/domain/auctionItem/service/AuctionItemServiceTest.java
Labels: test

#53 ✅ test : Scheduler 테스트 코드 추가
  src/main/java/io/dcns/wantitauction/domain/bid/entity/Bid.java
  src/test/java/io/dcns/wantitauction/global/scheduler/SchedulerTest.java
Labels: test

#55 ✅ test : adminService 테스트 코드 추가
  src/main/java/io/dcns/wantitauction/domain/admin/dto/AdminResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/admin/dto/UserPageableResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/admin/dto/UsersResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/admin/service/AdminService.java
  src/main/java/io/dcns/wantitauction/domain/user/dto/SignupRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/user/dto/UserResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/user/entity/User.java
  src/main/java/io/dcns/wantitauction/domain/user/repository/UserQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/user/service/KakaoService.java
  src/main/java/io/dcns/wantitauction/domain/user/service/UserService.java
  src/main/java/io/dcns/wantitauction/domain/user/viewController/KaKaoViewController.java
  src/main/resources/application.yml
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
  src/test/java/io/dcns/wantitauction/domain/admin/service/AdminServiceTest.java
  src/test/java/io/dcns/wantitauction/domain/user/UserCommonTest.java
  src/test/java/io/dcns/wantitauction/domain/user/service/UserServiceTest.java
Labels: bug, enhancement

#58 ♻️ 코드 리뷰 반영, @Qualifer로 빈을 명시적으로 등록
  src/main/java/io/dcns/wantitauction/global/config/RedisConfig.java
  src/main/java/io/dcns/wantitauction/global/jwt/RefreshTokenRepository.java
Labels: documentation

#59 사소한 오류 수정
  src/main/java/io/dcns/wantitauction/domain/bid/controller/BidController.java
  src/main/java/io/dcns/wantitauction/domain/bid/dto/BidRequestDto.java
  src/main/java/io/dcns/wantitauction/global/exception/ExceptionController.java
  src/main/java/io/dcns/wantitauction/global/scheduler/Scheduler.java
  src/main/java/io/dcns/wantitauction/global/sse/LiveBidController.java
  src/main/java/io/dcns/wantitauction/global/sse/LiveBidService.java
Labels: bug

#61 :sparkles: feat : BidService createBid 분산락 적용 추가
  src/main/java/io/dcns/wantitauction/domain/bid/service/BidService.java
  src/main/java/io/dcns/wantitauction/global/aop/Lock/LockAspect.java
  src/main/java/io/dcns/wantitauction/global/aop/Lock/Lockable.java
Labels: enhancement

#62 ♻️ refactor : SSE 로직 간소화
  src/main/java/io/dcns/wantitauction/global/sse/LiveBidService.java
Labels: enhancement

#60 :sparkles: 경매상품 조회시 , 레디스를 이용한 캐싱 처리
  build.gradle
  src/main/java/io/dcns/wantitauction/WantItAuctionApplication.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/AuctionItemPageableResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/AuctionItemService.java
  src/main/java/io/dcns/wantitauction/domain/user/controller/UserController.java
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailController.java
  src/main/java/io/dcns/wantitauction/domain/user/email/EmailService.java
  src/main/java/io/dcns/wantitauction/global/config/RedisConfig.java
  src/main/java/io/dcns/wantitauction/global/config/WebCorsConfig.java
  src/main/java/io/dcns/wantitauction/global/config/WebSecurityConfig.java
  src/main/java/io/dcns/wantitauction/global/redis/RedisConfig.java
  src/main/java/io/dcns/wantitauction/global/redis/RedisUtil.java
Labels: enhancement

#64 CI/CD 설정 반영
  .github/workflows/CICD.yml
  Dockerfile
  src/main/resources/application.yml
  src/test/java/io/dcns/wantitauction/domain/myAuctionItem/repository/AuctionItemRepositoryTest.java
Labels: documentation

#70 Feat/bid
  src/main/java/io/dcns/wantitauction/domain/point/dto/PointResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/point/service/PointService.java
  src/main/java/io/dcns/wantitauction/global/config/WebCorsConfig.java
Labels: documentation, enhancement

#72 S3 관련 기능 추가
  .github/workflows/CICD.yml
  Dockerfile
  build.gradle
  src/main/java/io/dcns/wantitauction/global/aws/s3/S3Config.java
  src/main/java/io/dcns/wantitauction/global/aws/s3/S3Controller.java
  src/main/java/io/dcns/wantitauction/global/aws/s3/S3Uploader.java
  src/main/resources/application.yml
Labels: bug, enhancement

#71 Feat/point
  src/main/java/io/dcns/wantitauction/domain/point/dto/PointResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/point/service/PointService.java
  src/main/java/io/dcns/wantitauction/domain/user/service/UserService.java
Labels: bug

#78 :sparkles: feat : 입찰 수 상위 3개 조회 기능 추가
  src/main/java/io/dcns/wantitauction/domain/bid/controller/BidController.java
  src/main/java/io/dcns/wantitauction/domain/bid/dto/TopAuctionItemsResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/bid/repository/BidQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/bid/service/BidService.java
  src/main/java/io/dcns/wantitauction/global/config/WebSecurityConfig.java
Labels: enhancement

#80 Feat/auctionItem 카테고리 컬럼 추가 및 진행중인 경매에서 카테고리 필터 기능 추가
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/AuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/AuctionItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/CreateProductRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/FinishedItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/InProgressItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/MyAuctionItemsResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/ReadyItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/UpdateMyItemRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/CategoryEnum.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/AuctionItemService.java
  src/main/java/io/dcns/wantitauction/domain/bid/dto/TopAuctionItemsResponseDto.java
  src/test/java/io/dcns/wantitauction/domain/auctionItem/service/AuctionItemServiceTest.java
Labels: enhancement

#81 내가 찜한(좋아요한) 상품 조회 API 수정
  src/main/java/io/dcns/wantitauction/domain/bid/dto/BidResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/bid/repository/BidQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/like/controller/LikeController.java
  src/main/java/io/dcns/wantitauction/domain/like/dto/LikeAuctionItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/like/repository/LikeQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/like/service/LikeService.java
  src/main/java/io/dcns/wantitauction/domain/user/controller/UserController.java
Labels: documentation

#91 🔧 chore : @JsonFormat 불필요하여 제거
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/CreateProductRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/UpdateMyItemRequestDto.java
Labels: chore

#92 🐛 bug : SSE 관련 구조 변경
  src/main/java/io/dcns/wantitauction/global/config/WebSecurityConfig.java
  src/main/java/io/dcns/wantitauction/global/sse/LiveBidController.java
  src/main/java/io/dcns/wantitauction/global/sse/LiveBidService.java
Labels: enhancement

#93 ✨ feat : 경매상품의 최고 호가 조회 API 추가
  src/main/java/io/dcns/wantitauction/domain/bid/controller/BidController.java
  src/main/java/io/dcns/wantitauction/domain/bid/dto/TopBidResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/bid/service/BidService.java
  src/main/java/io/dcns/wantitauction/global/config/WebSecurityConfig.java
Labels: enhancement

#94 :sparkles: feat : 입찰 조회 pageable 적용
  src/main/java/io/dcns/wantitauction/domain/bid/controller/BidController.java
  src/main/java/io/dcns/wantitauction/domain/bid/dto/BidPageableResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/bid/repository/BidQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/bid/service/BidService.java
  src/test/java/io/dcns/wantitauction/domain/bid/service/BidServiceTest.java
Labels: enhancement

#95 :wrench: chore : 코드 수정
  src/main/java/io/dcns/wantitauction/domain/pointLog/service/PointLogService.java
Labels: chore

#103 Debug/s3 nhs
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/MyAuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/MyAuctionItemService.java
  src/main/java/io/dcns/wantitauction/domain/notification/controller/NotificationController.java
  src/main/java/io/dcns/wantitauction/domain/notification/dto/NotificationRequestDto.java
  src/main/java/io/dcns/wantitauction/domain/notification/entity/Notification.java
  src/main/java/io/dcns/wantitauction/domain/notification/repository/NotificationRepository.java
  src/main/java/io/dcns/wantitauction/domain/notification/service/NotificationService.java
  src/main/java/io/dcns/wantitauction/global/aop/ForbiddenKeywords.java
  src/main/java/io/dcns/wantitauction/global/aws/s3/S3Controller.java
  src/main/java/io/dcns/wantitauction/global/aws/s3/S3Repository.java
  src/main/java/io/dcns/wantitauction/global/aws/s3/S3Service.java
  src/main/java/io/dcns/wantitauction/global/aws/s3/S3Uploader.java
  src/main/java/io/dcns/wantitauction/global/config/S3Config.java
  src/main/java/io/dcns/wantitauction/global/fcm/FCMInitializer.java
  src/main/java/io/dcns/wantitauction/global/scheduler/Scheduler.java
  src/main/java/io/dcns/wantitauction/global/utils/MultiPartUtils.java
  src/main/resources/application.yml
Labels: enhancement

#105 Feat/auction item nhs
  src/main/java/io/dcns/wantitauction/domain/auctionItem/controller/MyAuctionItemController.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/AuctionItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/FinishedItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/InProgressItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/MyAuctionItemsResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/dto/ReadyItemResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/entity/AuctionItem.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/repository/AuctionItemQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/auctionItem/service/MyAuctionItemService.java
  src/test/java/io/dcns/wantitauction/domain/myAuctionItem/service/MyAuctionItemServiceTest.java
Labels: enhancement

#107 ✅ test : test 변경
  src/test/java/io/dcns/wantitauction/domain/auctionItem/service/AuctionItemServiceTest.java
  src/test/java/io/dcns/wantitauction/domain/myAuctionItem/repository/AuctionItemRepositoryTest.java
  src/test/java/io/dcns/wantitauction/global/scheduler/SchedulerTest.java
Labels: test

#108 Test/bid BidServiceTest 수정
  src/test/java/io/dcns/wantitauction/domain/bid/service/BidServiceTest.java
Labels: test

#109 :white_check_mark: test : PointServiceTest 수정
  src/test/java/io/dcns/wantitauction/domain/point/service/PointServiceTest.java
Labels: test

#112 Feat/bid BidResponseDto에 imageUrl 추가
  src/main/java/io/dcns/wantitauction/domain/bid/dto/BidResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/bid/dto/TopAuctionItemsResponseDto.java
  src/main/java/io/dcns/wantitauction/domain/bid/repository/BidQueryRepository.java
  src/main/java/io/dcns/wantitauction/domain/bid/service/BidService.java
Labels: bug

#114 🩹 bug : 이미지 url 받아올 수 있게 변경
  src/main/java/io/dcns/wantitauction/domain/bid/repository/BidQueryRepository.java
Labels: chore
